"""baseline schema

Revision ID: a96cf2256884
Revises:
Create Date: 2026-06-23 19:11:54.498413

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "a96cf2256884"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        # pyrefly: ignore [implicit-import]
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        # pyrefly: ignore [implicit-import]
        sa.Column("registered_at", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        # pyrefly: ignore [implicit-import]
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        # pyrefly: ignore [implicit-import]
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        # pyrefly: ignore [implicit-import]
        sa.Column("thoughts", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        # pyrefly: ignore [implicit-import]
        sa.Column("path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        # pyrefly: ignore [implicit-import]
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        # pyrefly: ignore [implicit-import]
        sa.Column("ts", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        # pyrefly: ignore [implicit-import]
        sa.Column("msg", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        # pyrefly: ignore [implicit-import]
        sa.Column("extra", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        # pyrefly: ignore [implicit-import]
        sa.Column("to", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.session_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_messages_session_id"), ["session_id"], unique=False)

    op.create_table(
        "permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        # pyrefly: ignore [implicit-import]
        sa.Column("asker", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        # pyrefly: ignore [implicit-import]
        sa.Column("granter", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        # pyrefly: ignore [implicit-import]
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        # pyrefly: ignore [implicit-import]
        sa.Column("ask_why", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        # pyrefly: ignore [implicit-import]
        sa.Column("grant_why", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        # pyrefly: ignore [implicit-import]
        sa.Column("paths", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        # pyrefly: ignore [implicit-import]
        sa.Column("revoked_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        # pyrefly: ignore [implicit-import]
        sa.Column("revoked_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        # pyrefly: ignore [implicit-import]
        sa.Column("created_at", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        # pyrefly: ignore [implicit-import]
        sa.Column("updated_at", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asker"],
            ["sessions.session_id"],
        ),
        sa.ForeignKeyConstraint(
            ["granter"],
            ["sessions.session_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asker", "granter"),
    )
    with op.batch_alter_table("permissions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_permissions_granter"), ["granter"], unique=False)

    op.create_table(
        "thoughts",
        sa.Column("id", sa.Integer(), nullable=False),
        # pyrefly: ignore [implicit-import]
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        # pyrefly: ignore [implicit-import]
        sa.Column("ts", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        # pyrefly: ignore [implicit-import]
        sa.Column("thoughts", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        # pyrefly: ignore [implicit-import]
        sa.Column("extra", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.session_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("thoughts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_thoughts_session_id"), ["session_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("thoughts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_thoughts_session_id"))

    op.drop_table("thoughts")
    with op.batch_alter_table("permissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_permissions_granter"))

    op.drop_table("permissions")
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_messages_session_id"))

    op.drop_table("messages")
    op.drop_table("sessions")
    # ### end Alembic commands ###
